### ISSUE TITLE
crash in background dismissMessageView:completion:

### ISSUE THREAD

**Issue by CZyMfnIPC** [donileo/RMessage#4] opened 2016-03-04 15:26 UTC
We have a crash in production, we are having a hard time reproducing it in test.

The scenario is we put up an RMessage with endless duration on our rootViewController. Sometime after going to background (possibly when coming back into the app), it crashes.

To fix it we have set a high value for the duration rather than "EndlessDuration" in our RMessage because "didMoveToWindow" calls extra code only when it is set to Endless.

Stack trace:
1      MYAPPNAME 0x0000000100091f2c -[RMessage dismissMessageView:completion:] + 32
2   MYAPPNAME 0x0000000100093930 -[RMessageView didMoveToWindow] + 308
3   UIKit 0x00000001887b705c -[UIView(Internal) _didMoveFromWindow:toWindow:] + 1492
4   UIKit 0x00000001887b6d7c -[UIView(Internal) _didMoveFromWindow:toWindow:] + 756
5   UIKit 0x00000001887b6310 __45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke + 148
6   Foundation 0x00000001843e9500 -[NSISEngine withBehaviors:performModifications:] + 164
7   UIKit 0x00000001887b6194 -[UIView(Hierarchy) _postMovedFromSuperview:] + 528
8   UIKit 0x0000000188aca8c0 __UIViewWasRemovedFromSuperview + 224
9   UIKit 0x00000001887b4bb8 -[UIView(Hierarchy) removeFromSuperview] + 420
10  UIKit 0x0000000188b18dc0 __71-[UIPresentationController _initViewHierarchyForPresentationSuperview:]_block_invoke596 + 684
11  UIKit 0x0000000188b137e4 -[UIPresentationController transitionDidFinish:] + 120
12  UIKit 0x0000000188c3c530 -[_UICurrentContextPresentationController transitionDidFinish:] + 40
13  UIKit 0x0000000188b16e88 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke_2 + 184
14  UIKit 0x00000001888eb284 -[_UIViewControllerTransitionContext completeTransition:] + 112
15  UIKit 0x00000001888eb070 -[UITransitionView notifyDidCompleteTransition:] + 248
16  UIKit 0x00000001888eab6c -[UITransitionView _didCompleteTransition:] + 1160
17  UIKit 0x00000001888ea6cc -[UITransitionView _transitionDidStop:finished:] + 120
18  UIKit 0x00000001887f6e90 -[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 308
19  UIKit 0x00000001887f6d18 -[UIViewAnimationState animationDidStop:finished:] + 104
20  QuartzCore 0x00000001861cdc00 CA::Layer::run_animation_callbacks() + 280
21  libdispatch.dylib 0x000000018351d5f0 _dispatch_client_callout + 12
22  libdispatch.dylib 0x0000000183522cf8 _dispatch_main_queue_callback_4CF + 1840
23  CoreFoundation 0x0000000183a80bb0 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 8
24  CoreFoundation 0x0000000183a7ea18 __CFRunLoopRun + 1624
25  CoreFoundation 0x00000001839ad680 CFRunLoopRunSpecific + 380
26  GraphicsServices 0x0000000184ebc088 GSEventRunModal + 176
27  UIKit 0x0000000188824d90 UIApplicationMain + 200
28  MYAPPNAME 0x000000010003e2d4 main + 84
29  libdyld.dylib 0x000000018354e8b8 start + 0

**Comment by isadon** [comment] 2016-03-06 18:58
Thanks. Will look into it..

**Comment by isadon** [comment] 2016-05-22 21:51
Are you still having this issue? I would love to fix it but I can't reproduce it on my end either. I tried doing an endless duration on RMessage and then minimizing to the home screen then returning back but I'm not seeing a crash.

I went ahead and added a Modal Presentation View controller under "Present Modal" button of the Example Project for testing this issue, the commit for that is https://github.com/donileo/RMessage/commit/73703fd5cce69369b169d115ad2a8f066e85a2b6. You can play around with that to see if you can invoke the crash you are getting. For example you can present modally then present an endless duration message view then dismiss. You can also present an endless in the main view controller then present a modal over it.

I went ahead and played around with it a bit but was not able to induce a crash. As a side note the example i mentioned above definitely triggers the window being removed from the message view (but no crash) so thats a good thing.

**Comment by CZyMfnIPC** [comment] 2016-05-23 01:49
Unfortunately we were never able to reliably get the crash while testing to debug further. I will give your test project a try.

**Comment by isadon** [comment] 2016-06-02 17:10
@CraZyMuffinIPC I will close this issue out. Please reopen if you can reproduce and some more info.

**Closed as completed by isadon** 2016-06-02 17:10 UTC
