### ISSUE TITLE
Title and Subtitle with Custom Font

### ISSUE THREAD

**Issue by PawanmSpaceo** [donileo/RMessage#54] opened 2019-01-09 09:09 UTC
How to set the custom font to title and subtitle and also with font size?

**Comment by isadon** [comment] 2019-01-09 12:56
Please look at the README for how to create a Spec which is used for RMessage styling. The fields you want to set are titleFont and bodyFont.

**Comment by PawanmSpaceo** [comment] 2019-01-10 08:59
Thanks for answering

I can't able to find any Spec class or function. I'm using the latest version :(

**Comment by isadon** [comment] 2019-01-15 12:44
```
let rControl = RMController()

// Customize the message, by using the DefaultRMessageSpec as your base.
// The DefaultRMessageSpec object is a struct with default values for a
// "default" RMessageSpec styling. All we need to do is pick up the the defaults
// from it and then just specify which variables we want customized. For a list
// of all the possible vars take a look at its definition!
var customSpec = DefaultRMessageSpec()
customSpec.backgroundColor = .red
customSpec.titleColor = .white
customSpec.bodyColor = .white
customSpec.iconImage = UIImage(named: "MyIcon.png")

// How about a custom spec based on the predefined warningSpec but with
// attributed string attributes for the title and body text?
var attrWarningSpec = warningSpec
attrWarningSpec.titleAttributes = [.backgroundColor: UIColor.red, .foregroundColor: UIColor.white]
attrWarningSpec.bodyAttributes = [
.backgroundColor: UIColor.blue, .foregroundColor: UIColor.white,
.underlineStyle: NSUnderlineStyle.styleSingle.rawValue,
]

// Now lets present Tell the RMController to present the message with your custom stylings.
rControl.showMessage(
      withSpec: customSpec,
      title: "I'm custom",
      body: "Nice!"
    )
```

Please look at how the customSpec variable is created and then the fields are set.

**Comment by PawanmSpaceo** [comment] 2019-01-16 04:07
Use of unresolved identifier 'DefaultRMessageSpec' 
Even I have written import RMessage

**Comment by isadon** [comment] 2019-01-16 05:49
Thanks, for letting me know I will check soon what the issue is.

**Comment by PawanmSpaceo** [comment] 2019-01-16 10:00
Let me know, once u solve that issue.

**Comment by isadon** [comment] 2019-01-29 16:14
Hi, sorry for the long delay. Please use the develop branch and test if your issue now fixed.

**Comment by PawanmSpaceo** [comment] 2019-01-30 04:07
Thanks, Should I update the pod to use?

**Comment by isadon** [comment] 2019-01-30 15:17
To use the develop branch in your Podfile do:

Pod 'RMessage' , :git => 'https://github.com/donileo/RMessage.git', :branch => 'develop'.

Then see if it works for you.
-- 
Adonis

**Comment by PawanmSpaceo** [comment] 2019-01-31 04:10
You are awesome @donileo, it's working now
Thanks for solving the issue...

**Closed as completed** 2019-02-01 05:30 UTC
