### ISSUE TITLE
[Issue] [iPhone X] Notification banner is too short, doesn't extend down far enough to display title.

### ISSUE THREAD

**Issue by harrytutorful** [donileo/RMessage#49] opened 2018-06-05 15:24 UTC
Hi there!

I just started testing on iPhone X and noticed that the top banner (when no nav bar is present) doesn't extend down far enough to show the title and description properly.

This is obviously due to the weird new height measurements of iPhone X's nav bar but I was wondering if this is already a solved issue or if there's something I should be specifically doing to solve this?

Thanks!

This is the code I'm using:

```
[RMessage showNotificationWithTitle:@"Important account change"
                               subtitle:@"You have been logged out due to an important account change."
                                   type:RMessageTypeCustom
                         customTypeName:mProfileStyleKey
                               callback:nil];
```

**Comment by isadon** [comment] 2018-06-05 18:22
Does the issue happen on the simulator or the actual device? Can you also post a screenshot?

**Comment by harrytutorful** [comment] 2018-06-06 08:31
![screen shot 2018-06-06 at 09 29 03 2](https://user-images.githubusercontent.com/35488004/41026384-55e9c0fe-696c-11e8-907b-821b3bcef825.png)

This is just on simulator, as I don't have an X to hand.

**Comment by isadon** [comment] 2018-06-07 04:44
Are you sure you are using the latest release? Can you please test on master and the develop branch and tell me your results.

**Comment by harrytutorful** [comment] 2018-06-08 11:51
Just tried develop branch, and I was already using master branch on 2.3.0. 

Same result I'm afraid.

`pod 'RMessage', :git => 'https://github.com/donileo/RMessage.git', :branch => 'develop'`

**Comment by isadon** [comment] 2018-06-08 16:40
Can you post a sample project inducing the issue for you? That’s the quickest way for me to check why this issue occurs for you.

**Comment by afrizal7** [comment] 2018-07-16 07:15
I also experienced this problem. On iPhone X, when the navigation bar is hidden, the notification banner would not be displayed properly. I tested this on the simulator, and I use version 2.3.1.

**Comment by sssandyad** [comment] 2018-07-16 07:53
@donileo this can easily reproduce on iPhone X simulator while the navigation bar is hidden
![screen shot 2018-07-16 at 14 50 20 2](https://user-images.githubusercontent.com/6153272/42747773-ef6b78ac-8907-11e8-971a-7dde8a2d8b07.png)

while the navigation bar is not hidden, it would display correctly
![screen shot 2018-07-16 at 14 52 06 2](https://user-images.githubusercontent.com/6153272/42747800-07ad57aa-8908-11e8-96e5-0451e070f3b9.png)

**Comment by isadon** [comment] 2018-07-21 05:12
@sssandyad I am not seeing this issue on my end. Can you guys send a sample project.

**Comment by sssandyad** [comment] 2018-07-23 09:11
Hi @donileo,
After further investigation, I found out that the problem is from our own project. I solved it already :)
Thanks!

**Comment by harrytutorful** [comment] 2018-07-23 09:13
Oo @sssandyad what did you find to be the solution if you don't mind?

**Comment by sssandyad** [comment] 2018-07-23 12:35
@harrytutorful I created simple project (https://github.com/sssandyad/testRMessage) as an example to reproduce the bug. But as @donileo said, It can't be reproduced. 

So I suspected the problem is from our side and it must be related to auto layout stuff and yet I am aware that there are some hacky codes to updating layout view in our project.

I found out that when the navigation bar is hidden, RMessage will be subview of `view` from view controller
![screen shot 2018-07-23 at 19 24 07](https://user-images.githubusercontent.com/6153272/43076370-36237050-8eae-11e8-9cad-f6148d1f1548.png)

while the navigation bar is not hidden, RMessage will be subview of `UILayoutContainerView` from navigation controller
![screen shot 2018-07-23 at 19 20 47](https://user-images.githubusercontent.com/6153272/43076422-66930cb4-8eae-11e8-8b13-f35335af8dbe.png)

It's rather hacky but here the solutions I can propose for you:
 1. override `viewDidLayoutSubview`, get RMessageView from there and set its frame origin y position, or
 2.  override `viewDidLayoutSubview`, get RMessageView from there and remove constraints and set it again with the appropriate constraint

**Comment by isadon** [comment] 2018-07-23 15:47
@sssandyad Without any changes to your project (without the supposed fix you posted above). Who is the parent view of RMessage for you in your project in the case when the issue happens?

@harrytutorful Same question to you.

**Comment by sssandyad** [comment] 2018-07-24 03:37
@donileo it is the same as the sample project. The parent view is `view` from view controller
<img width="739" alt="screen shot 2018-07-24 at 10 33 49" src="https://user-images.githubusercontent.com/6153272/43115268-5a6ab4a8-8f2d-11e8-8e00-afd420da7ff0.png">

**Comment by isadon** [comment] 2018-07-25 17:34
Can you guys tell me what the ```safeAreaInsets``` property of your view controller's view is right before calling RMessage to present on it? 

You can call a line like this to show what I need:
```
NSLog(@"insets are: %@", NSStringFromUIEdgeInsets(yourViewControllerHere.view.safeAreaInsets));
```

Also when are you calling RMessage to present in your view controller? RMessage depends on the safeAreaInsets property of your view to properly present and decide how big to size itself. But according to the Apple docs the safeAreaInsets property might be 0 (which would cause the issue you are seeing) if your view hasn't been fully presented when calling RMessage. That may be the reason why this is happening.

**Comment by sssandyad** [comment] 2018-07-27 03:22
@donileo in my case, the view controller has feature that when user scrolling down, it will hides navigation bar and when user scrolling up, it will shows the navigation bar. The problem is while RMessage is displaying and I scroll it up or down, the RMessage layout will be broken. My question is why RMessage parent view is different in case of show/hide navigation bar? Is that expected?

**Comment by isadon** [comment] 2018-08-02 18:02
>@donileo in my case, the view controller has feature that when user scrolling down, it will hides navigation bar and when user scrolling up, it will shows the navigation bar. The problem is while RMessage is displaying and I scroll it up or down, the RMessage layout will be broken. My question is why RMessage parent view is different in case of show/hide navigation bar? Is that expected?

@sssandyad I think your specific case is a bit more different. When RMessage presents it binds to the navigation bar using auto layout, given that in your scenario you are dynamically moving your Navigation bar around its most likely tripping RMessage somehow. This is most likely an RMessage bug but for me to fix it the fastest way would be to send me an Xcode project showing the issue. Doing this will just help me save time fixing the problem considering I’m very busy with other dev things right now.

If you guys cant duplicate the issue in an xcodeproj then you will really really have to give me some time to properly diagnose and fix the root cause of how this issue is occurring for you. Rest assured though I really want to fix this 🙂.

**Comment by isadon** [comment] 2018-08-04 07:05
@sssandyad there should be some coming changes that will probably fix this soon!

**Comment by isadon** [comment] 2018-08-04 23:11
@sssandyad @harrytutorful  Ok. Please test develop and tell me if this issue still exists for you. I believe cf0473f3d6 should do something 😀.

**Comment by sssandyad** [comment] 2018-08-09 10:37
Awesome! It works like a charm. Thanks 😄 @donileo

**Comment by isadon** [comment] 2018-08-19 10:12
Closing Issue. If not truly fixed feel free to reopen.

**Closed as completed by isadon** 2018-08-19 10:12 UTC
