### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by dtomicAZ** [donileo/RMessage#39] opened 2018-02-23 12:18 UTC
Hi,

I again have crash of RMessage:
pod 'RMessage', :git => 'https://github.com/donileo/RMessage.git', :commit => '9e87b0d'

It's on the line 1127 of the RMessageView.m (self.topToVCLayoutConstraint.active = YES;)

Here I am sending you video where I am uploading files, then showing success message.
First file went well, but second got stuck. (Sometimes first got stuck)

I think it's something due UITableView reload and showing RMessage in "same time".

video: https://streamable.com/mecc8

**Comment by isadon** [comment] 2018-02-23 12:24
Can you please send me an example project with this crash so that I may debug this issue?

**Comment by dtomicAZ** [comment] 2018-02-23 12:40
@donileo today I don't have a time. I am back to 7cda71e which is working good.

I'll try make example project in Monday.

**Comment by isadon** [comment] 2018-02-26 09:52
Hi @dtomicAZ quick question: What version of iOS are you running when you get this crash?

**Comment by dtomicAZ** [comment] 2018-02-26 09:54
@donileo 11.2.5

**Comment by isadon** [comment] 2018-02-26 09:55
is this a crash you are getting through the simulator or a device running 11.2.5?

**Comment by dtomicAZ** [comment] 2018-02-26 10:05
@donileo both, on simulator, as well on device.

Here is use case:
user fetch list of documents,
then user upload some document, 
then I show Rmessage,
then immediately after showing Rmessage I call API for fetch list of documents, which triggers tableview reload, and here crash happens.

**Comment by isadon** [comment] 2018-02-26 10:15
Ok, I still need the example project. Thanks.

**Comment by isadon** [comment] 2018-02-27 12:16
Are you presenting by passing in a viewController such as showNotificationInViewController? Can you paste here how you are presenting RMessage and in what method you are calling it? for example viewDidLoad, viewWillAppear?

**Comment by dtomicAZ** [comment] 2018-02-27 12:24
@donileo 

```
class RMessageImpl: NSObject, AlertProtocol {
  
  func showAlert(title: String, subTitle: String?, type: AlertType) {
    
    var alertType = RMessageType.error
    if type == .success { alertType = RMessageType.success }
    if type == .warning { alertType = RMessageType.warning }

    RMessageView.appearance().titleSubtitleLabelsSizeToFit = subTitle != nil ? false : true
    
    RMessage.showNotification(withTitle: title, subtitle: subTitle, type: alertType, customTypeName: nil, callback: nil)
  }
}
```

I am calling it After I press button:
 request on server is made, response come, then I call method:

`func showAlert(title: String, subTitle: String?, type: AlertType)`

and after that I call `tableview.reloadData()`

**Comment by isadon** [comment] 2018-02-27 12:55
Can you use the showNotification method that passes in a view controller and pass in your top level view controller? Do you still get a crash? Without you providing me an example project or a lot more detail as to how to reproduce it will be hard for me to fix this issue.

**Comment by isadon** [comment] 2018-02-28 04:00
Can you please pull develop and tell me if the issue still exists for you? Its possible the crash is resolved but check to see if RMessage still continues working afterward.

**Comment by dtomicAZ** [comment] 2018-02-28 07:53
@donileo Now Crash is not occurring, that is great.

There is a small glitch sometimes occurring.

Check this video, at 6th second:
https://streamable.com/moxha

But it's important that Crash is resolved, this glitch is acceptable.

**Comment by isadon** [comment] 2018-02-28 18:26
Ok thanks. Like I said previously, can you present with showNotificationInViewController instead and tell me if the glitch exists? What most likely seems to be happening is that RMessage’s superview is being removed from it while it is trying to dismiss.

I may have have one more patch to help mitigate the issue more but if RMessage’s superview is getting removed while its presenting/dismissing that may really be something that needs to be fixed on your end to reduce the glitch.

**Comment by dtomicAZ** [comment] 2018-03-02 12:20
@donileo If I use:
RMessage.showNotification(in: self, title: "Dokument prilozen", subtitle: nil, type: .success, customTypeName: nil, callback: nil)

than all is ok, no glitch.

**Comment by isadon** [comment] 2018-03-14 08:04
If you are no longer getting a crash can you please close this issue? Thanks!

**Closed as completed** 2018-03-26 07:21 UTC
